src/Web/Controllers/BeestjesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DomainServices.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BeestjesController : BaseController
    {
        private readonly IBeestjeService _beestjeService;
        private readonly IAccessoireService _accessoireService;


        public BeestjesController(ApplicationDbContext db, IBeestjeService beestjeService,
            IAccessoireService accessoireService) : base(db)
        {
            _beestjeService = beestjeService;
            _accessoireService = accessoireService;
        }

        // GET: Beestjes
        public async Task<IActionResult> Index()
        {
            await _beestjeService.GetBeestjes();
            return View(await _beestjeService.GetBeestjes());
        }


        // GET: Beestjes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beestjes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Type,Price,Image")] Beestje beestje)
        {
            if (!ModelState.IsValid) return View(beestje);
            
            await _beestjeService.CreateBeestje(beestje);
            return RedirectToAction(nameof(Index));

        }

        // GET: Beestjes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var beestje = await _beestjeService.GetBeestje(id);
            if (beestje == null)
                return NotFound();


            return View(beestje);
        }


        // GET: Beestjes/Edit/5
        public async Task<IActionResult> AddAccessoires(int id)
        {
            var beestje = await _beestjeService.GetBeestje(id);
            if (beestje == null)
                return NotFound();


            ViewBag.Accessoires = await _accessoireService.GetAccessoires();
            return View(beestje);
        }


        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAccessoires(int id, [Bind("Accessoires")] List<int> accessoires)
        {
            var beestje = await _beestjeService.GetBeestje(id);

            beestje = await _beestjeService.SelectAccessoires(beestje, accessoires);
            ViewBag.Accessoires = await _accessoireService.GetAccessoires();
            return View(beestje);
        }


        // POST: Beestjes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Type,Price,Image")] Beestje beestje)
        {
            await _beestjeService.EditBeestje(id, beestje);
            return View(beestje);
        }

        // GET: Beestjes/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var beestje = await _beestjeService.GetBeestje(id);
            if (beestje == null)
                return NotFound();

            return View(beestje);
        }

        //POST: Accessoires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _beestjeService.DeleteBeestje(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/Views/Beestjes/AddAccessoires.cshtml
@model Models.Beestje
@{
    ViewData["Title"] = "AddAccessoires";
}

<h1>Accessoires</h1>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Accessoires toevoegen of verwijderen
            </div>

        @using (Html.BeginForm("AddAccessoires", "Beestjes", FormMethod.Post))
        {
            <div class="card-body" style="padding-left: 40px">

                @foreach (var item in ViewBag.Accessoires)
                {
                    <div class="checkbox">
                        <label>
                            <input class="form-check-input" type="checkbox" name="Accessoires" value="@item.Id" @(Model.BeestjeAccessoires.Select(x => x.AccessoireId).ToList().Contains(item.Id) ? "checked" : "")>
                            @item.Name
                        </label>
                    </div>
                }

            </div>

            <div class="card-footer">
                <div class="row">
                    <div class="col-lg-6 text-left align-content-center">
                        <a asp-action="Index">Terug naar lijst</a>
                    </div>
                    <div class="col-lg-6 text-right">
                        <input type="submit" value="Opslaan" class="btn btn-success"/>
                    </div>
                </div>
            </div>
        }
        </div>
    </div>
</div>

src/Web/Views/Beestjes/Create.cshtml
@model Models.Beestje

@{
    ViewData["Title"] = "Create";
}

<h1>Nieuw beestje aanmaken</h1>

<h4>Beestje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Nieuwe accessoire maken
            </div>
            <form asp-action="Create">
                <div class="card-body">
                 
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Type" class="control-label"></label>
                            @Html.DropDownList("Type", 
                                Html.GetEnumSelectList<Models.Type>(),
                                "Select Type",new { @class = "form-control" })
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Price" class="control-label"></label>
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Image" class="control-label"></label>
                            <input asp-for="Image" class="form-control" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-lg-6 text-left align-content-center">
                            <a asp-action="Index">Terug naar lijst</a>
                        </div>
                        <div class="col-lg-6 text-right">
                            <input type="submit" value="Aanmaken" class="btn btn-success"/>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Web/Views/Beestjes/Delete.cshtml
@model Models.Beestje

@{
    ViewData["Title"] = "View";
}

<h1>Beestje verwijderen</h1>

<h3>Weet je zeker dat je dit wilt verwijderen?</h3>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Beestje verwijderen
            </div>
            <div class="card-body">
                <div class="form-group">
                    <b>@Html.DisplayNameFor(model => model.Name)</b>
                    @Html.DisplayFor(model => model.Name)
                </div>
                <dd class="col-sm-10">

                </dd>
                <div class="form-group">
                    <b>@Html.DisplayNameFor(model => model.Type)</b>
                    @Html.DisplayFor(model => model.Type)
                </div>
                <dd class="col-sm-10">
                </dd>
                <div class="form-group">
                    <b>@Html.DisplayNameFor(model => model.Price)</b>
                    @Html.DisplayFor(model => model.Price)
                </div>

                <div class="form-group">
                    <b>@Html.DisplayNameFor(model => model.Image)</b>
                    @Html.DisplayFor(model => model.Image)
                </div>
            </div>
            <div class="card-footer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
                    <a asp-action="Index">Terug naar lijst.</a>
                </form>
            </div>
        </div>
    </div>
</div>

src/Web/Views/Beestjes/Edit.cshtml
@model Models.Beestje

@{
    ViewData["Title"] = "Edit";
}

<h1>Beestje bewerken</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Beestje bewerken
            </div>

            <form asp-action="Edit">
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        @Html.DropDownList("Type",
                            Html.GetEnumSelectList<Models.Type>(),
                            "Select Type", new { @class = "form-control" })
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Price" class="control-label"></label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Image" class="control-label"></label>
                        <input asp-for="Image" class="form-control" />
                        <span asp-validation-for="Image" class="text-danger"></span>
                    </div>

                    <a asp-action="AddAccessoires" asp-route-id="@Model.Id">Accessoires toevoegen</a>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-lg-6 text-left align-content-center">
                            <a asp-action="Index">Terug naar lijst</a>
                        </div>
                        <div class="col-lg-6 text-right">
                            <input type="submit" value="Opslaan" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Web/Views/Beestjes/Index.cshtml
@model IEnumerable<Models.Beestje>

@{
    ViewData["Title"] = "BeestjesList";
}

<h1>Beestjes</h1>
<p>
    <a asp-action="Create">Nieuw beestje aanmaken</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Bewerken</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Verwijderen</a>
            </td>
        </tr>
}
    </tbody>
</table>